#- platform: opengarage
#  covers:
#    garage:
#      host: 192.168.2.129
#      device_key: !secret og
#      name: garage
- platform: aladdin_connect
  username: !secret alun
  password: !secret alpw
