#switch.yaml#

- platform: command_line
  switches:
    aeotec_zstick_disco_light:
      friendly_name: 'Aeotech Z-Stick Disco Light'
      command_on: 'echo -e -n "\x01\x08\x00\xF2\x51\x01\x01\x05\x01\x50" > /dev/serial/by-id/usb-0658_0200-if00'
      command_off: 'echo -e -n "\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51" > /dev/serial/by-id/usb-0658_0200-if00'

- platform: rest
  name: shelly_doorbell_chime_status
  resource: http://192.168.2.21/settings/relay/0
  body_on: 'btn_type=toggle'
  body_off: 'btn_type=detached'
  is_on_template: '{{ value_json.btn_type == "toggle" }}'